apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9090
      name: "service"
      targetPort: 9000
    - port: 9001
      name: "console"
      targetPort: 9001
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        ports:
        - containerPort: 9000
          hostPort: 9090
        - containerPort: 9001
          hostPort: 9001
        args:
        - server
        - /data
        - "--console-address"
        - :9001
        env:
          - name: MINIO_DOMAIN
            value: dat515.devmode.app
        volumeMounts:
        - name: minio-persistent-storage
          mountPath: /data
      volumes:
      - name: minio-persistent-storage
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
