apiVersion: v1
kind: Service
metadata:
  name: peertube
spec:
  selector:
    app: peertube
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: peertube-config
data:
  production.yaml: |
    transcoding:
      enable: true
      resolutions:
        360p: true
        480p: true
        720p: true
        1080p: true
        1440p: true
        2160p: true
      hls:
        enabled: true

    import:
      videos:
        http:
          enabled: true

    auto_blacklist:
      videos:
        of_users:
          enabled: false

    contact_form:
      enabled: false

    signup:
      enabled: true
      requires_approval: true
      requires_email_verification: false

    redis:
      hostname: 'redis'
      port: 6379
      auth: null

    webserver:
      https: true
      hostname: dat515.devmode.app
      #port: 443
    object_storage:
      enabled: true
      endpoint: 'dat515.devmode.app'

      web_videos:
        bucket_name: 'peertube-videos'
        prefix: 'web-videos/'

      streaming_playlists:
        bucket_name: 'peertube-videos'
        prefix: 'streaming-playlist/'
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peertube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peertube
  template:
    metadata:
      labels:
        app: peertube
    spec:
      hostAliases:
        - ip: 10.10.10.3
          hostnames:
            - "peertube-videos.dat515.devmode.app"
      containers:
      - name: peertube
        image: chocobozzz/peertube:production-bullseye
        imagePullPolicy: Always
        env:
          - name: PEERTUBE_DB_HOSTNAME
            value: postgresql
          - name: PEERTUBE_DB_USERNAME
            value: <username>
          - name: PEERTUBE_DB_PASSWORD
            value: <password>
          - name: PEERTUBE_DB_SSL
            value: "false"
          - name: PEERTUBE_ADMIN_EMAIL
            value: dat515@devmode.app
          - name: PEERTUBE_WEBSERVER_HOSTNAME
            value: dat515.devmode.app
          - name: PEERTUBE_SECRET
            value: <secret>
          - name: AWS_ACCESS_KEY_ID
            value: <key_id>
          - name: AWS_SECRET_ACCESS_KEY
            value: <key_secret>
          - name: PT_INITIAL_ROOT_PASSWORD
            value: <password>
        ports:
        - containerPort: 9000
          hostPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /config/production.yaml
          readOnly: true
          subPath: production.yaml
        - name: peertube-persistent-storage
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: peertube-config
      - name: peertube-persistent-storage
        persistentVolumeClaim:
          claimName: peertube-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peertube-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
