apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        command: 
          - "redis-server"
          - "--save"
          - "20"
          - "1"
          - "--loglevel"
          - "warning"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: localhost:5000/lab1_image:latest
        imagePullPolicy: Always
        env:
          - name: CELERY_BROKER_URL
            value: amqp://user:password@rabbitmq:5672
        ports:
        - containerPort: 80
        command: 
          - "python3"
          - "website.py"
